server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vip?serverTimezone=GMT%2b8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 数据库下划线自动转驼峰标示关闭56

files:
  upload:
    path: C:\Users\jinzong53\Desktop\SoftResource\DBNU\springboot\files\

# using for start python's file by anaconda's Vevn
anaconda:
  path:
    detect: C:\Users\jinzong53\Desktop\Project\detect.py
    treat: C:\Users\jinzong53\Desktop\Project\treat.py
    predict: C:\Users\jinzong53\Desktop\Project\predict.py
    python-evn: D:\Programs\Anaconda3\envs\pytorch\python.exe


